name: Auto Lint with Reviewdog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  autolint:
    name: Run autolint
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      #- name: Install autolint
      #  run: npm install -g autolint

      - name: Run autolint with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          autolint . 2>&1 | tee autolint.log
