name: Delete Topic

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: actions/checkout@v4
      - name: Delete topic
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}

