name: Check Commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commits-for-jira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get PR commit messages
      id: get_commit_messages
      run: |
        BASE=${{ github.event.pull_request.base.ref }}
        HEAD=$(git rev-parse HEAD)

        echo "BASE: $BASE"
        echo "HEAD: $HEAD"

        COMMIT_MESSAGES=$(git log origin/$BASE..$HEAD --pretty=format:"%s")

        echo "---- Commit Messages ----"
        echo "$COMMIT_MESSAGES"
        echo "-------------------------"

        VALID=false
        while IFS= read -r line; do
          echo "Checking commit: $line"
          #if echo "$line" | grep -Eq '[A-Z]{2,10}-[0-9]+'; then
          if echo "$line" | grep -Eq 'Issue #[0-9]+'; then
            VALID=true
            break
          fi
        done <<< "$COMMIT_MESSAGES"

        if [ "$VALID" = "false" ]; then
          echo "No commit messages contain a valid issue tracker id."
          exit 1
        else
          echo "At least one commit message contains a issue tracker id."
        fi
