name : Check Commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commit-message-check-job:
    runs-on: ubuntu-latest
    name: Commit
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - id: check-commit
        uses: uptownaravi/verify-commit-message-action@v2
        with:
          regex: '(?i)jira-[0-9]{3,}'
