name : Hello World

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          gcc hello.c -o hello.o
      - name: Test
        run: |
          ./hello.o
